export const SEC_COMPANY_QUEUE = "SEC_COMPANY_QUEUE";
export const SEC_COMPANY_HOLDING_QUEUE = "SEC_COMPANY_HOLDING_QUEUE";

export const SEC_COMPANY_SCHEDULER_ID = "SEC_COMPANY_SCHEDULER";
export const SEC_COMPANY_HOLDING_SCHEDULER_ID = "SEC_COMPANY_HOLDING_SCHEDULER";